version: '3.8'

services:
  wpdb:
    container_name: wordpress-mysql
    image: mysql:8.0
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - '5306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
  wordpress:
    container_name: wordpress  
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_HOST: wpdb
    ports:
      - "8083:80"
    depends_on:
      - wpdb
    volumes:
      ["./wp_data:/var/www/html"]
  phpmyadmin:
    container_name: wordpress-pma  
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_HOST: wpdb
      # PMA_ARBITRARY: 1
      # PMA_USER: exampleuser
      # PMA_PASSWORD: examplepassword
    ports:
      - "8084:80"
    depends_on:
      - wpdb
volumes:
  db_data:
  wp_data: